### ISSUE TITLE
Self-XSS when naming clip with HTML/JavaScript content

### ISSUE THREAD

**Issue by freddyb** [mdn/web-dictaphone#1]
Most likely due to https://github.com/mdn/web-dictaphone/blob/gh-pages/scripts/app.js#L66.

I suggest using textContent or createTextNode instead.

**Comment by chrisdavidmills** [comment]
Wow, I hadn't seen this comment until now! The code has changed since you wrote this, but I'm assuming you are referring my rather naughty usage of innerHTML. I'll use textContent instead.

Cheers.
