### ISSUE TITLE
The audio controls are not working as expected just after stop recordig

### ISSUE THREAD

**Issue by ergauravgoyal** [mdn/web-dictaphone#10]
Once a user records the audio the progress bar is showing abnormal behaviour when it plays for first time while for second time onwards it's working as expected ..

**Comment by chrisdavidmills** [comment]
What browser are you trying this with? It works for me.

**Comment by ergauravgoyal** [comment]
Hi,

I am using chrome

**Comment by chrisdavidmills** [comment]
I've had another look. I can see the issue you are describing in Chrome release (v57), but Chrome Canary (v60) seems to be OK. So I am guessing this is a regression that has since been fixed.
