### ISSUE TITLE
How to get Recording File in mp3 or Wav format

### ISSUE THREAD

**Issue by ergauravgoyal** [mdn/web-dictaphone#11]
Hi,

We want to get a recording in mp3 or .wav format.How can I achieve it?

Regards,
Gaurav

**Comment by chrisdavidmills** [comment]
This API is the easiest way to get started:

https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API

Once you have the blob created containing your media, it is up to you to capture it - e.g. put it into an <audio> tag, or into a download link, or send it to a server-side script and use that capture it to disk.

browsers tend to capture the audio in their default format, but you can set the mimetype of the recording container when you create the MediaRecorder object: https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/MediaRecorder
