### ISSUE TITLE
How to save recorded voice in host as a file?

### ISSUE THREAD

**Issue by MahdiIsComing** [mdn/web-dictaphone#15]

**Comment by oyusufa** [comment]
I need same thing, can you help me? I want to save the wav file in the host

**Comment by JTerry7** [comment]
Same here, any answer for this?

**Comment by chrisdavidmills** [comment]
I am not sure you can create the MP3 file on the client-side. To do this, I think you'd have to send your audio blob up to the server and do it there, using a language like Node.js

This tutorial seems quite useful: https://medium.com/jeremy-gottfrieds-tech-blog/javascript-tutorial-record-audio-and-encode-it-to-mp3-2eedcd466e78

**Comment by moshfeu** [comment]
I implemented uploading using php in [a fork](https://github.com/moshfeu/web-dictaphone).

**Comment by schalkneethling** [comment]
Nice work @moshfeu!  

Hey @MahdiIsComing! Thank you for opening this issue. Please see https://github.com/mdn/web-dictaphone/issues/15#issuecomment-640510740 and also  https://github.com/mdn/web-dictaphone/issues/15#issuecomment-823856615. We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository.
