### ISSUE TITLE
Variables declaration without var keyword

### ISSUE THREAD

**Issue by ggerico** [mdn/web-dictaphone#18]
In the app.js file on lines 135, 136 :
```javascript
WIDTH = canvas.width
HEIGHT = canvas.height;
```
There are variables declaration without var keyword in uppercase. 
Is it on purpose ? 

Tks ~
Germain

**Comment by chrisdavidmills** [comment]
That's a mistake — there should be const keywords there. I've added those in.

The UPPERCASE convention is usually used for simple constant values that are key to the app, but will never change, to make it clear that they are constant. I've left them in for now.

Thanks for reporting this!
