### ISSUE TITLE
Ability to close the stream once record stops

### ISSUE THREAD

**Issue by obonyojimmy** [mdn/web-dictaphone#19]
- Add some code demostrating closing the _mediaDevices_,  MediaStream when MediaRecorder stops.
- Get the Blob withf the default  mime encoding of the MediaRecorder using , `MediaRecorder.requestData()` . instead of having to manually get blob from chunks, to ensure compact data intergrity.

**Comment by schalkneethling** [comment]
Hey @obonyojimmy! Thank you for opening this issue, and your suggestions. We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/) repository. Please open a new issue or pull request once the content of this repository has been moved. Thank you.
