### ISSUE TITLE
How to download the sound clip?

### ISSUE THREAD

**Issue by yltang52** [mdn/web-dictaphone#2]
I noticed that the following code in index.html has been commented. How do I download the recorded sound clips? Thanks.

```
  <article class="clip">
    <audio controls></audio>
    <a href="">Download clip</a>
  </article>
```

**Comment by chrisdavidmills** [comment]
I started thinking about this, but never worked it out fully. After creating the object URL, you could open that URL in a new window and save it from there, but that's hardly ideal UX ;-)

**Comment by zhishaofei3** [comment]
a.href = window.URL.createObjectURL(blob);
