### ISSUE TITLE
Ask for microphone permission when record button is pressed 

### ISSUE THREAD

**Issue by jamiethewebguy** [mdn/web-dictaphone#21]
It would be nice to delay the 'use microphone' permissions dialog box the browser displays until the user presses the record button as opposed to the permissions dialog box opening on page load. The former might scare the user.

**Comment by schalkneethling** [comment]
Hey @jamiethewebguy! Thank you for opening this issue and your suggestion. We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/) repository. Please open a new issue or pull request once the content of this repository has been moved. Thank you.
