### ISSUE TITLE
not recording long audios in Firefox 

### ISSUE THREAD

**Issue by loguz3** [mdn/web-dictaphone#22]
recordking ok in chrome, but in Firefox 87 it doesn't record audios longer than 6 - 7 seconds, the time changes sometimes audios are shorter. When recording it doesn't show any error. But once it finishes the audio is cut.

**Comment by chrisdavidmills** [comment]
It works fine for me in Firefox; I can't reproduce this error. I am using Firefox 88 on macOS.

Try using the latest Nightly version to see if it works for you there. If so, it may have been a regression that then got fixed.

If you are on a different OS, maybe it is an OS-specific bug? If you are still getting this problem, then submit a Firefox bug at https://bugzilla.mozilla.org.

**Comment by loguz3** [comment]
Thank you very much for your answer, indeed, I did the test with the nightly versions 88 and 89 and it works flawlessly in both of them, in Windows 10.

**Comment by chrisdavidmills** [comment]
@loguz3 cool, good to hear

**Comment by andion** [comment]
I reproduced this error using Firefox 87.0 (64 bits) in Mac OS (11.2.3 Big Sur). It's not the same actually, it seems it records part of the stream, not all. Maybe a tiny amount.

I spotted the error while using the MediaStream Recording API to create a React audio recording component. It worked correctly in Chrome based browsers, but in Firefox it was recording only part of the stream. Came to the web-dictaphone example to check wether it would work properly on Firefox and the same thing happened here.

**Comment by andion** [comment]
I tried the same app and the dictaphone app with Firefox Dev edition (88.0b9 64-bit) and the bug it's not present there. The dictaphone example app works perfect too. 

It looks a lot like a temporal bug in 87.0, if not I guess there would be lots of bugs on this matter. I hope this helps someone and that someone could fix the issue by updating his FF version.

Edit: It also has to do with the format I was recording the audio. The test that did not work in 87.0 was recording 'audio/ogg' like web-dictaphone does. Using 'audio/mp3' it works just fine.
