### ISSUE TITLE
How to upload this audio to aws?

### ISSUE THREAD

**Issue by hungcuiga1** [mdn/web-dictaphone#23]
Hello @chrisdavidmills Thank you for great project. This is my question, Can you help me ,please? thank you so much.

**Comment by schalkneethling** [comment]
Hey @hungcuiga1! Thank you for opening this issue. We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository. For this specific question, I would invite you to pose this on either [Matrix](https://matrix.to/#/#mdn:mozilla.org) or [Discourse](https://discourse.mozilla.org/c/mdn/236).
