### ISSUE TITLE
 latency issue

### ISSUE THREAD

**Issue by simonreger** [mdn/web-dictaphone#26]
Hello, I want to record multiple tracks based on the tracks before. For example: In the first track I recorded a beatbox, and when recording the second track, the first track plays in the headphones and I record the lyrics in sync with it. When playing it both at the same time, I notice that the second track begins a few milliseconds later. Can this problem be fixed?

Heres the Code: https://www.regerapps.de/recorder/

**Comment by schalkneethling** [comment]
Hey @simonreger! Thank you for opening this issue. We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository. For this specific question, I would invite you to pose this on either [Matrix](https://matrix.to/#/#mdn:mozilla.org), [Discourse](https://discourse.mozilla.org/c/mdn/236), or [StackOverflow](https://stackoverflow.com/questions/tagged/web-audio-api).
