### ISSUE TITLE
Doesn't work in Windows 8.1 Chrome or Android 4.4.2 Chrome 42.0.2311.111 

### ISSUE THREAD

**Issue by d668** [mdn/web-dictaphone#3]

**Comment by d668** [comment]
Uncaught TypeError: Cannot read property 'checkInstalled' of undefined
anonymous function) @ install.js:21

```
var installCheck = navigator.mozApps.checkInstalled(manifest_url);
```

Uncaught ReferenceError: MediaRecorder is not definedonSuccess @ app.js:30

```
var mediaRecorder = new MediaRecorder(stream);
```

**Comment by chrisdavidmills** [comment]
Hi there,

MediaRecorder is not supported on Chrome/Android as yet — just Firefox for now. there is now a W3C spec available, and other browsers are considering implementation. See https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder_API for full details of the API.
