### ISSUE TITLE
preload does not work with recorded audio, duration is NaN until full played first time

### ISSUE THREAD

**Issue by ottodevs** [mdn/web-dictaphone#9]
When we record a sound from the microphone, the recorded audio clip has not defined its .duration property, also tried with preload="metadata" or preload="auto" without success...
It seems that the recorded file has something wrong inside the file binary data that prevents the audio player, or the <audio> container to read its duration property...

How to reproduce: 
Record an audio snippet from the microphone. Check that the player has not defined the "duration" for the file. audio.duration = NaN

Tried with diferent audio formats, like audio/ogg, audio/wav, audio/mpeg and audio/mp3
Play the file one time. Now you can check the duration is defined.
Is the problem in the stream, the blob or the chunks?

**Comment by avrebarra** [comment]
@ottodevs Perhaps did you use Chrome? I've read somewhere that this is a bug within Chrome's audio recording behavior. There is this [Chrome issue page](https://bugs.chromium.org/p/chromium/issues/detail?id=642012) and also highlighted [here](http://air.ghost.io/recording-to-an-audio-file-using-html5-and-js/). Maybe it's because of that?

Sorry if I'm pointing out the wrong thing.

**Comment by shauryaverma4296** [comment]
Yeah I'm using chrome and the issue still exist. Please help me fix this @ottodevs @shrotavre @robhudson @sole @chrisdavidmills 
![audio error](https://user-images.githubusercontent.com/13284683/35259893-4d4b5aa4-002e-11e8-9206-0d131d76c83f.png)

**Comment by warmachine7733** [comment]
import React from "react";
import "./index.css";
import { Link } from "react-router-dom";

class AudioPlayer extends React.Component {
  render() {
    const { url, title, cover, artist } = this.props.audio;
    const { play, pauseAndPlay } = this.props;
    console.log("props in indi", this.props);

    return (
      <div>
        <Link to="/" style={{ color: "black" }}>
          <i
            style={{ position: "absolute", top: "1.5%", left: "2%" }}
            className="material-icons"
          >
            keyboard_backspace
          </i>
        </Link>

        <div className="musicPlayer">
          <audio
            controls
            preload="metadata"
            ref={ref => (this.player = ref)}
            // style={{ display: "none" }}
            autoPlay
          >
            <source src={`http://localhost:4000/${url}`} type="audio/mp3" />
            Your browser does not support the audio tag.
          </audio>
          <div className="thumbnail">
            <img
              style={{ maxWidth: "100%", maxHeight: "550px" }}
              src="default.jpg"
              alt="thumbnail"
            />
          </div>
          <div className="details">
            <h3>{title}</h3>
            <h5>{artist}</h5>
          </div>
          <div className="timerAndProgress">
            <div className="timer">0:30</div>
            <div className="progressBar">
              <progress className="progress" value="20" max="100"></progress>
            </div>
            <div className="container controls">
              <div className="row">
                <div className=" col-3 shuffle">
                  <i className="material-icons" style={{ fontSize: "40px" }}>
                    shuffle
                  </i>
                </div>
                <div className=" col-3 previous">
                  <i className="material-icons" style={{ fontSize: "40px" }}>
                    skip_previous
                  </i>
                </div>
                <div className="col-3 playAndPause">
                  <i
                    className="material-icons"
                    style={{ fontSize: "40px" }}
                    onClick={pauseAndPlay}
                  >
                    {play ? "pause" : "play_arrow"}
                  </i>
                </div>
                <div className="col-3 ext">
                  <i className="material-icons" style={{ fontSize: "50px" }}>
                    skip_next
                  </i>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }
  componentDidMount() {
   console.log("nextProps", this.player.duration);
  }
  shouldComponentUpdate(nextProps) {
    console.log("nextProps", this.player.duration);
    if (nextProps.play) {
      this.player.play();
    } else {
      this.player.pause();
    }
    return true;
  }
}

export default AudioPlayer;
`i am also getting the same issue Nan in ComponentDidMount then getting the value in shouldComponentUpdate`

**Comment by abidhkm** [comment]
any fix for this ?

**Comment by chrisdavidmills** [comment]
I've checked this again, and it seems to work fine for me , in both Fx and Chrome.

I just updated the code the remove the old FxOS install functionality (no longer needed), and to make it so that the AudioContext object instance is only created in response to the REcord button being clicked, to satisy the new API requirements.
